### ISSUE TITLE
Support private functions

### ISSUE THREAD

**Issue by h4cc** [narrowtux/loppers#7]

**Comment by narrowtux** [comment]
Does this not work? https://github.com/narrowtux/loppers/blob/master/test/examples/defp.ex
https://github.com/narrowtux/loppers/blob/master/test/walk_tree_test.exs#L105

**Comment by h4cc** [comment]
@gerritwalther plz test

**Comment by gerritwalther** [comment]
You can add parsers including `defp` methods.
