### ISSUE TITLE
Should -> be added to special forms?

### ISSUE THREAD

**Issue by batate** [narrowtux/loppers#8]
I am happy to submit a pull request for this one. Here's the test case. Case and cond require ->. 

Test case: 

iex(1)> code = 
...(1)> """
...(1)> case animal do
...(1)>   :cat -> "meow"
...(1)>   :dog -> "arf"
...(1)> end
...(1)> """
"case animal do\n  :cat -> \"meow\"\n  :dog -> \"arf\"\nend\n"
iex(2)> Code.eval_string code, [animal: :dog]
{"arf", [animal: :dog]}
iex(3)> {_status, quoted} = Code.string_to_quoted code
{:ok,
 {:case, [line: 1],
  [
    {:animal, [line: 1], nil},
    [
      do: [
        {:->, [line: 2], [[:cat], "meow"]},
        {:->, [line: 3], [[:dog], "arf"]}
      ]
    ]
  ]}}
iex(4)> Loppers.validate quoted, whitelist: Loppers.special_forms
{:error,
 [
   not_allowed: {:->, [line: 3], [[:dog], "arf"]},
   not_allowed: {:->, [line: 2], [[:cat], "meow"]}
 ]}
iex(5)> Loppers.validate quoted, whitelist: Loppers.special_forms ++ [:->]
:ok

**Comment by narrowtux** [comment]
yeah that's probably a good idea.

**Comment by narrowtux** [comment]
implemented in https://github.com/narrowtux/loppers/pull/9
